[tool.poetry]
name = "pyprland"
version = "1.2.0"
description = "An hyperland plugin system"
authors = ["fdev31 <fdev31@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "pyprland"}]
homepage = "https://github.com/hyprland-community/pyprland/"

[tool.poetry.scripts]
pypr = "pyprland.command:main"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
