[tool.poetry]
name = "pyprland"
version = "1.5.1"
description = "Hyperland plugin system - batteries included"
authors = ["fdev31 <fdev31@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "pyprland"}]
homepage = "https://github.com/hyprland-community/pyprland/"

[tool.poetry.scripts]
pypr = "pyprland.command:main"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
