[tool.poetry]
name = "pyprland"
version = "2.2.7"
description = "Hyperland plugin system - batteries included"
authors = ["fdev31 <fdev31@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "pyprland"}]
homepage = "https://github.com/hyprland-community/pyprland/"

[tool.poetry.scripts]
pypr = "pyprland.command:main"

[tool.poetry.dependencies]
python = "^3.11"
aiofiles = "^23.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"
pytest-mock = "^3.12.0"
pdoc = "^14.4.0"
mypy = "^1.8.0"
vulture = "^2.11"
pylint = "^3.0.3"
coverage = "^7.4.1"
pydantic = "^2.6.1"
black = "^24.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
